import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Canvas} from "@react-three/fiber";
import React from "react";
import Wall from "../features/components/wall";
import {OrbitControls} from "@react-three/drei";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Canvas className={styles.canvas}  dpr={[1, 1.5]}>
            <pointLight position={[10, 10, 10]} />
            <ambientLight intensity={0.2} position={[10, 10, 10]} />
            <Wall />
            <OrbitControls />
          </Canvas>
      </main>
    </div>
  )
}

export default Home
