import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Canvas} from "@react-three/fiber";
import React from "react";
import Box from "../features/components/box";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Canvas className={styles.canvas}>
              <pointLight position={[10, 10, 10]} />
              <Box />
          </Canvas>
      </main>
    </div>
  )
}

export default Home
